version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: natalia
      MONGO_INITDB_ROOT_PASSWORD: 123456
